### PR TITLE
Use correct number of particles in Optimal Filter and add MPI test

### LINKED ISSUE #209: OptimalFilter BoundsError when running with mpiexecjl
Getting a BoundsError when running the OptimalFilter with mpiexecjl.
```
$ mpiexecjl -n 2 julia test_swe.jl
```
The output when running the latest master [version](https://github.com/DanGiles/ParticleDA.jl/tree/master) (tdac solver):
```
ERROR: LoadError: BoundsError: attempt to access 51×51×100 view(::Array{Float64, 4}, :, :, 1, :) with eltype Float64 at index [1:51, 1:51, 101]
Stacktrace:
  [1] throw_boundserror(A::ERROR: SubArray{Float64, 3, Array{Float64, 4}, Tuple{Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}, Int64, Base.Slice{Base.OneTo{Int64}}}, false}, I::Tuple{Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}, Int64})
    @ Base ./abstractarray.jl:651
  [2] checkbounds
    @ ./abstractarray.jl:616 [inlined]
  [3] view
    @ ./subarray.jl:177 [inlined]
  [4] calculate_mean_height!(mean::Array{Float64, 3}, height::SubArray{Float64, 3, Array{Float64, 4}, Tuple{Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}, Int64, Base.Slice{Base.OneTo{Int64}}}, false}, offline_matrices::ParticleDA.OfflineMatrices{Matrix{Float64}, Vector{Float64}, Matrix{ComplexF64}}, observations::Vector{Float64}, stations::LoadError: NamedTuple{(:nst, :ist, :jst), Tuple{Int64, Vector{Int64}, Vector{Int64}}}, grid::ParticleDA.Grid{Float64}, grid_ext::ParticleDA.Grid{Float64}, fft_plan::FFTW.cFFTWPlan{ComplexF64, -1, false, 2, UnitRange{Int64}}, fft_plan!::FFTW.cFFTWPlan{ComplexF64, -1, true, 2, UnitRange{Int64}}, filter_params::ParticleDA.Default_params.FilterParameters{Float64}, obs_noise_std::Float64)
    @ ParticleDA ~/.julia/dev/ParticleDA/src/OptimalFilter.jl:330
  [5] sample_height_proposal!(height::SubArray{Float64, 3, Array{Float64, 4}, Tuple{Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}, Int64, Base.Slice{Base.OneTo{Int64}}}, false}, offline_matrices::ParticleDA.OfflineMatrices{Matrix{Float64}, Vector{Float64}, Matrix{ComplexF64}}, online_matrices::ParticleDA.OnlineMatrices{Vector{ComplexF64}, Matrix{ComplexF64}, Array{Float64, 3}}, observations::Vector{Float64}, stations::NamedTuple{(:nst, :ist, :jst), Tuple{Int64, Vector{Int64}, Vector{Int64}}}, grid::ParticleDA.Grid{Float64}, grid_ext::ParticleDA.Grid{Float64}, fft_plan::FFTW.cFFTWPlan{ComplexF64, -1, false, 2, UnitRange{Int64}}, fft_plan!::FFTW.cFFTWPlan{ComplexF64, -1, true, 2, UnitRange{Int64}}, filter_params::ParticleDA.Default_params.FilterParameters{Float64}, rng::Random.MersenneTwister, obs_noise_std::Float64)
    @ ParticleDA ~/.julia/dev/ParticleDA/src/OptimalFilter.jl:361
  [6] update_particle_proposal!(model_data::Main.Model.ModelData{Main.Model.ModelParameters{Float64}, Main.Model.StateVectors{Array{Float64, 4}, Array{Float64, 3}}, Main.Model.ObsVectors{Vector{Float64}, Matrix{Float64}}, Main.Model.StationVectors{Vector{Int64}}, Array{Float64, 4}, Vector{Main.Model.RandomField{GaussianRandomFields.GaussianRandomField{GaussianRandomFields.CirculantEmbedding, GaussianRandomFields.CovarianceFunction{2, GaussianRandomFields.Matern{Float64}}, Tuple{StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}}, Matrix{Float64}, Tuple{Matrix{Float64}, FFTW.cFFTWPlan{ComplexF64, -1, true, 2, UnitRange{Int64}}}}, Array{Float64, 3}, Array{ComplexF64, 3}, Array{Float64, 3}}}, Main.Model.LLW2d.Matrices{Float64, Matrix{Float64}}, Vector{Random.MersenneTwister}}, filter_data::NamedTuple{(:weights, :resampling_indices, :statistics, :avg_arr, :var_arr, :copy_buffer, :offline_matrices, :online_matrices, :stations, :grid, :grid_ext, :rng, :obs_noise_std, :fft_plan, :fft_plan!), Tuple{Vector{Float64}, Vector{Int64}, Array{ParticleDA.SummaryStat{Float64}, 3}, Array{Float64, 3}, Array{Float64, 3}, Array{Float64, 4}, ParticleDA.OfflineMatrices{Matrix{Float64}, Vector{Float64}, Matrix{ComplexF64}}, ParticleDA.OnlineMatrices{Vector{ComplexF64}, Matrix{ComplexF64}, Array{Float64, 3}}, NamedTuple{(:nst, :ist, :jst), Tuple{Int64, Vector{Int64}, Vector{Int64}}}, ParticleDA.Grid{Float64}, ParticleDA.Grid{Float64}, Vector{Random.MersenneTwister}, Float64, FFTW.cFFTWPlan{ComplexF64, -1, false, 2, UnitRange{Int64}}, FFTW.cFFTWPlan{ComplexF64, -1, true, 2, UnitRange{Int64}}}}, filter_params::ParticleDA.Default_params.FilterParameters{Float64}, truth_observations::Vector{Float64}, nprt_per_rank::Int64, filter_type::OptimalFilter)
    @ ParticleDA ~/.julia/dev/ParticleDA/src/ParticleDA.jl:395
  [7] macro expansion
    @ ~/.julia/packages/TimerOutputs/SSeq1/src/TimerOutput.jl:252 [inlined]
  [8] run_particle_filter(init::typeof(Main.Model.init), filter_params::ParticleDA.Default_params.FilterParameters{Float64}, model_params_dict::Dict{Any, Any}, filter_type::OptimalFilter; rng::Nothing)
    @ ParticleDA ~/.julia/dev/ParticleDA/src/ParticleDA.jl:476
  [9] run_particle_filter(init::Function, user_input_dict::Dict{Any, Any}, filter_type::OptimalFilter; rng::Nothing)
    @ ParticleDA ~/.julia/dev/ParticleDA/src/ParticleDA.jl:624
 [10] run_particle_filter(init::Function, path_to_input_file::String, filter_type::OptimalFilter; rng::Nothing)
    @ ParticleDA ~/.julia/dev/ParticleDA/src/ParticleDA.jl:607
 [11] run_particle_filter(init::Function, path_to_input_file::String, filter_type::OptimalFilter)
    @ ParticleDA ~/.julia/dev/ParticleDA/src/ParticleDA.jl:592
 [12] top-level scope
    @ ~/.julia/dev/ParticleDA/test_swe.jl:20
in expression starting at /Users/dangiles/.julia/dev/ParticleDA/test_swe.jl:20
```
The test_swe.jl file:

```Julia
# Load ParticleDA
using ParticleDA
#
# # Save some variables for later use
test_dir = joinpath("test")
module_src = joinpath(test_dir, "model", "model.jl")
input_file = joinpath(test_dir,"input.yaml")
# # Instantiate the test environment
using Pkg
Pkg.activate(test_dir)
Pkg.instantiate()

# Include the sample model source code and load it
include(module_src)
using .Model
run_particle_filter(Model.init, input_file, OptimalFilter())
```

and input.yaml file:
```Julia
filter:
  nprt: 200
  n_time_step: 400
  verbose: true
  enable_timers: true
  output_filename: "test.h5"

model:
  llw2d:
    x_length: 200.0e3
    y_length: 200.0e3
    nx: 51
    ny: 51
    station_filename: "stationsW1.txt"
    nobs: 15
    obs_noise_std: 0.01

    nu: 2.5
    lambda: 5.0e3
    sigma : [0.1, 10.0, 10.0]

    nu_initial_state: 2.5
    lambda_initial_state: 5.0e3
    sigma_initial_state: 0.001

    n_integration_step: 10
    time_step: 5.0

    peak_height: 30.0
    peak_position: [1e4,1e4]
    cutoff_depth: 500.0
```

Please note this is also occurring for the latest [speedy](https://github.com/DanGiles/ParticleDA.jl/tree/dg/speedy) implementation but the referenced indices in the BoundsError are different.

### PR DESCRIPTION
**Pull request by tkoskela**
Optimal Filter does not do any global operations over particles, so we can simply substitute `nprt_per_rank` for `filter_params.nprt`. This has an added benefit of not having to pass `filter_params` at all to most functions, since `nprt` was the only field being used.

Optimal Filter is now included in the tests in `mpi.jl`, so we should at least catch MPI errors a bit sooner.

Also removed verbose output from the MPI test, didn't see any reason to have it. Unless someone disagrees? The MPI test also enables timers, do we want to keep that?

Closes #209

### CODE REVIEW

File: src/OptimalFilter.jl [hunk 1]
```diff
@@ -351,22 +351,22 @@ function sample_height_proposal!(height::AbstractArray{T,3},
...
                                  fft_plan::FFTW.FFTWPlan,
                                  fft_plan!::FFTW.FFTWPlan,
-                                 filter_params,
+                                 nprt_per_rank::Int,
                                  rng::Random.AbstractRNG,
                                  obs_noise_std::T,
                                  ) where T
 
-    @assert iseven(filter_params.nprt) "Number of particles must be even"
+    @assert iseven(nprt_per_rank) "Number of particles per rank must be even to use the Optimal Filter"
```
Comment (giordano) [inline src/OptimalFilter.jl:359]: :ok_hand: improving  the error message.  Maybe also show the value found?  Something like
```suggestion
    @assert iseven(nprt_per_rank) "Number of particles per rank must be even to use the Optimal Filter, found $(nprt_per_rank)"
```

**Review by giordano — APPROVED** [review]
Thanks for fixing this!  Looks overall good to me :+1: 

> Also removed verbose output from the MPI test, didn't see any reason to have it. Unless someone disagrees?

I seem to remember we had `verbose=true` to make sure also I/O works correctly when using MPI.

> The MPI test also enables timers, do we want to keep that?

I like to have a look at those timings, yes.

We have another loop over all particles in `get_log_weights!`:
https://github.com/Team-RADDISH/ParticleDA.jl/blob/5613c3ae0cc557cc4c6291f9075c59c63e285170/src/OptimalFilter.jl#L404
That one should be fine?

File: src/OptimalFilter.jl (hunk 1 above)
Comment (tkoskela) [reply src/OptimalFilter.jl:359]: Would be even better if we also showed the rank that found it, but it seems like we are not using MPI here

**Comment by tkoskela** [comment]
> We have another loop over all particles in get_log_weights!:
> ParticleDA.jl/src/OptimalFilter.jl
>
> Line 404 in 5613c3a
> 
> for iprt in 1:nprt 
> 
> That one should be fine?

Yes, this `nprt` is declared on the previous line

File: test/mpi.jl [hunk 2]
```diff
@@ -28,15 +29,21 @@ params = Dict(
...
 
 # Warmup
-rm("particle_da.h5"; force = true)
 run_particle_filter(Model.init, params, BootstrapFilter())
 # Flush a newline
 println()
 
 # Run the command
-rm("particle_da.h5"; force = true)
+params["filter"]["output_filename"] = "bootstrap_filter.h5"
```
Comment (giordano) [inline test/mpi.jl:37]: Maybe drop a comment here to remind us why we want to enable writing the output file?  Something like
```suggestion
# Write output file to make sure it works correctly when using multiple MPI ranks
params["filter"]["output_filename"] = "bootstrap_filter.h5"
```
